# This is a basic workflow to help you get started with Actions

name: Todays date

# Controls when the workflow will run
on:
  schedule:
    - cron:  '00 3,15 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo $(date +%Y%m%d%H%M)
