# This is a basic workflow to help you get started with Actions

name: Web Request Action

# Controls when the workflow will run
on:
  # Triggers the workflow on a schedule
  schedule:
    - cron:  '00 4,16 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
 
    runs-on: ubuntu-latest

    steps:
      - name: GET Request
        uses: satak/webrequest-action@master
        with:
          url: https://my-json-server.typicode.com/typicode/demo/posts
          method: GET
