# This is a basic workflow to help you get started with Actions

name: Web Request Action

# Controls when the workflow will run
on:
  # Triggers the workflow on a schedule
  schedule:
    - cron:  '00 4,16 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
 
    runs-on: ubuntu-latest

    steps:
      - name: GET Request
        uses: satak/webrequest-action@master
        with:
          url: https://services.nvd.nist.gov/rest/json/cves/1.0/?pubStartDate=2022-06-07T13:00:00:000 UTC%2B01:00&pubEndDate=2022-06-09T13:36:00:000 UTC%2B01:00
          method: GET
