name: "Hit a webhook"
 
on:
  push:
    tags:
      - '**'
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://services.nvd.nist.gov/rest/json/cves/1.0/"
